services:
  stor24-cms:
    build: .
    container_name: stor24-cms
    restart: unless-stopped
    environment:
      - PAYLOAD_SECRET=440723c7a04f856ccc2f807f7db249208cbaf3bd963b180a9d081bb50c819e14
      - DATABASE_URI=postgresql://stor4_user:stor4_pass@stor4_db:5432/stor4_db
    networks:
      - root_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stor24-cms.rule=Host(`cms.stor4.srv938083.hstgr.cloud`)"
      - "traefik.http.routers.stor24-cms.entrypoints=websecure"
      - "traefik.http.routers.stor24-cms.tls=true"
      - "traefik.http.routers.stor24-cms.tls.certresolver=mytlschallenge"
      - "traefik.http.services.stor24-cms.loadbalancer.server.port=3000"
      - "traefik.docker.network=root_default"
networks:
  root_default:
    external: true
