services:
  stor24-cms:
    build: .
    container_name: stor24-cms
    restart: unless-stopped
    environment:
      - PAYLOAD_SECRET=${PAYLOAD_SECRET}
      - DATABASE_URI=${DATABASE_URI}
    volumes:
      - stor24_media:/app/media
    networks:
      - root_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stor24-cms.rule=Host(`cms.stor4.srv938083.hstgr.cloud`)"
      - "traefik.http.routers.stor24-cms.entrypoints=websecure"
      - "traefik.http.routers.stor24-cms.tls=true"
      - "traefik.http.routers.stor24-cms.tls.certresolver=mytlschallenge"
      - "traefik.http.services.stor24-cms.loadbalancer.server.port=3000"
      - "traefik.docker.network=root_default"
networks:
  root_default:
    external: true
volumes:
  stor24_media:
