/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    'content-ideas': ContentIdea;
    'storage-insights': StorageInsight;
    users: User;
    media: Media;
    posts: Post;
    faqs: Faq;
    areas: Area;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'content-ideas': ContentIdeasSelect<false> | ContentIdeasSelect<true>;
    'storage-insights': StorageInsightsSelect<false> | StorageInsightsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    areas: AreasSelect<false> | AreasSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    'homepage-hero': HomepageHero;
  };
  globalsSelect: {
    'homepage-hero': HomepageHeroSelect<false> | HomepageHeroSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Make room for your next good idea. Plan useful content here before creating an article, guide or FAQ. Ideas stay private to your CMS team.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-ideas".
 */
export interface ContentIdea {
  id: number;
  /**
   * A working title or a question your customers ask.
   */
  title: string;
  /**
   * The phrase a customer might type into Google. Check it in Search Console.
   */
  keyword?: string | null;
  /**
   * For example, people moving home or businesses storing stock.
   */
  audience?: string | null;
  /**
   * What will readers learn? Note the angle, useful answers and the next step you want them to take.
   */
  brief?: string | null;
  /**
   * Save customer questions, Search Console findings, source links and facts to check. Do not assume search volumes or rankings.
   */
  research?: string | null;
  /**
   * Paste the STOR24 page link once the content is published. Changing an idea’s status does not publish a page.
   */
  publishedUrl?: string | null;
  status: 'idea' | 'researching' | 'ready' | 'writing' | 'published' | 'parked';
  format: 'guide' | 'article' | 'faq' | 'location';
  priority: 'high' | 'normal' | 'low';
  targetDate?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * In-depth guides that help customers plan, pack and find the right storage. Manage the writing, images and search details in one place.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "storage-insights".
 */
export interface StorageInsight {
  id: number;
  title: string;
  /**
   * e.g. self-storage-johannesburg-guide
   */
  slug: string;
  /**
   * Pillar Guides are the 8 main long-form guides. Cluster Pages are supporting articles.
   */
  pageType: 'pillar' | 'cluster';
  /**
   * For Cluster Pages: which Pillar Guide this supports.
   */
  relatedPillar?: (number | null) | StorageInsight;
  /**
   * Short summary shown on the Storage Insights hub card (1-2 sentences).
   */
  excerpt: string;
  heroImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * For editorial/QA reference - documents which pages this content should link to.
   */
  internalLinks?:
    | {
        /**
         * Page name or path, e.g. /storage-prices-johannesburg
         */
        targetPage?: string | null;
        anchorText?: string | null;
        id?: string | null;
      }[]
    | null;
  seoTitle: string;
  metaDescription: string;
  primaryKeyword: string;
  secondaryKeywords?:
    | {
        keyword?: string | null;
        id?: string | null;
      }[]
    | null;
  searchIntent?: ('informational' | 'commercial' | 'transactional' | 'mixed') | null;
  ctaHeading?: string | null;
  ctaText?: string | null;
  ctaButtonLabel?: string | null;
  ctaButtonLink?: string | null;
  /**
   * Review the guide before setting it to Published.
   */
  status: 'draft' | 'published';
  publishedDate?: string | null;
  /**
   * Which JSON-LD schema blocks to render for this page.
   */
  schemaTypes?: ('Article' | 'FAQPage' | 'BreadcrumbList' | 'LocalBusiness' | 'Service')[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Your website photography and artwork. Upload a clear, high-quality image and add a short description for accessibility.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe what is in the image. This helps people using screen readers and makes your library easier to understand.
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * People with access to this content studio. Website customers and staff operations are managed in the CRM.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * News, stories and practical advice. Open an article to edit its content, imagery and search information.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Use lowercase words separated by hyphens. Changing a published address can break existing links.
   */
  slug: string;
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  featuredImage?: (number | null) | Media;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Check the article before setting it to Published.
   */
  status: 'draft' | 'published';
  publishedAt?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Helpful answers for the website. Keep each question specific and each answer clear.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: string;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Local content for the areas you serve. Explain the benefits for both personal and business storage.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "areas".
 */
export interface Area {
  id: number;
  name: string;
  slug: string;
  intro: string;
  personalCopy?: string | null;
  businessCopy?: string | null;
  nearby?:
    | {
        area?: string | null;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'content-ideas';
        value: number | ContentIdea;
      } | null)
    | ({
        relationTo: 'storage-insights';
        value: number | StorageInsight;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'areas';
        value: number | Area;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-ideas_select".
 */
export interface ContentIdeasSelect<T extends boolean = true> {
  title?: T;
  keyword?: T;
  audience?: T;
  brief?: T;
  research?: T;
  publishedUrl?: T;
  status?: T;
  format?: T;
  priority?: T;
  targetDate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "storage-insights_select".
 */
export interface StorageInsightsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  pageType?: T;
  relatedPillar?: T;
  excerpt?: T;
  heroImage?: T;
  content?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  internalLinks?:
    | T
    | {
        targetPage?: T;
        anchorText?: T;
        id?: T;
      };
  seoTitle?: T;
  metaDescription?: T;
  primaryKeyword?: T;
  secondaryKeywords?:
    | T
    | {
        keyword?: T;
        id?: T;
      };
  searchIntent?: T;
  ctaHeading?: T;
  ctaText?: T;
  ctaButtonLabel?: T;
  ctaButtonLink?: T;
  status?: T;
  publishedDate?: T;
  schemaTypes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  featuredImage?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  status?: T;
  publishedAt?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "areas_select".
 */
export interface AreasSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  intro?: T;
  personalCopy?: T;
  businessCopy?: T;
  nearby?:
    | T
    | {
        area?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Manage the opening section of stor24.co.za. Saved changes can take up to five minutes to appear. Check both desktop and mobile after updating.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage-hero".
 */
export interface HomepageHero {
  id: number;
  eyebrow: string;
  headlinePrimary: string;
  headlineAccentLineOne: string;
  headlineAccentLineTwo: string;
  bodyCopy: string;
  slides?:
    | {
        /**
         * Landscape JPG, PNG or WebP. Minimum 1200 × 800px; accepted ratio 6:5 to 8:5.
         */
        desktopImage: number | Media;
        /**
         * Optional portrait crop, minimum 720 × 900px. Desktop image is used when empty.
         */
        mobileImage?: (number | null) | Media;
        alt: string;
        fit: 'contain' | 'cover';
        position: 'left' | 'center' | 'right';
        id?: string | null;
      }[]
    | null;
  rotationEnabled?: boolean | null;
  rotationIntervalSeconds?: number | null;
  ctaEyebrow: string;
  ctaStrong: string;
  ctaButtonLabel: string;
  ctaButtonLink: string;
  benefitsHeading: string;
  benefits?:
    | {
        icon: 'access' | 'camera' | 'flex' | 'people';
        title: string;
        copy: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage-hero_select".
 */
export interface HomepageHeroSelect<T extends boolean = true> {
  eyebrow?: T;
  headlinePrimary?: T;
  headlineAccentLineOne?: T;
  headlineAccentLineTwo?: T;
  bodyCopy?: T;
  slides?:
    | T
    | {
        desktopImage?: T;
        mobileImage?: T;
        alt?: T;
        fit?: T;
        position?: T;
        id?: T;
      };
  rotationEnabled?: T;
  rotationIntervalSeconds?: T;
  ctaEyebrow?: T;
  ctaStrong?: T;
  ctaButtonLabel?: T;
  ctaButtonLink?: T;
  benefitsHeading?: T;
  benefits?:
    | T
    | {
        icon?: T;
        title?: T;
        copy?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}